
SELECT 
dbo.FCRMVI.FCRMVI_MODAPL + dbo.FCRMVI.FCRMVI_CODAPL + CONVERT(VARCHAR, dbo.FCRMVI.FCRMVI_NROAPL) + dbo.FCRMVI.FCRMVI_TIPPRO + dbo.FCRMVI.FCRMVI_ARTCOD + ISNULL(dbo.FCRMVP.USR_FCRMVP_ESTPCK, 'A') + ISNULL(dbo.FCRMVP.FCRMVP_NUBICA, '') + ISNULL(dbo.FCRMVP.FCRMVP_NDESPA, '') AS ID, 
dbo.FCRMVH.USR_FCRMVH_SITIOS AS SITIOS, 
dbo.FCRMVH.FCRMVH_CIRCOM AS CIRCOM, 
dbo.FCRMVP.FCRMVP_DEPOSI AS DEPOSI, 
dbo.FCRMVI.FCRMVI_CODAPL AS CODFOR, 
dbo.FCRMVI.FCRMVI_NROAPL AS NROFOR, 
dbo.FCRMVH.FCRMVH_NROCTA AS NROCTA, 
dbo.FCRMVI.FCRMVI_TIPPRO AS TIPPRO, 
dbo.FCRMVI.FCRMVI_ARTCOD AS ARTCOD, 
dbo.STTTPH.STTTPH_DESCRP AS TIPDES, 
dbo.STMPDH.STMPDH_DESCRP AS DESCRP,
(SUM(FCRMVP_CANTID)) AS CANTID,       
ISNULL(dbo.FCRMVP.USR_FCRMVP_CNTPCK, 0) AS CNTPCK, 
ISNULL(dbo.FCRMVP.USR_FCRMVP_CNTFST, 0) AS CNTFST, 
ISNULL(dbo.FCRMVP.USR_FCRMVP_USRPCK, '') AS USRPCK, 
ISNULL(dbo.FCRMVP.USR_FCRMVP_ESTPCK, 'A') AS ESTPCK, 
ISNULL(dbo.FCRMVP.USR_FCRMVP_CNTPK2, 0) AS CNTPK2, 
dbo.FCRMVP.USR_FCRMVP_USRPK2 AS USRPK2,
ISNULL(dbo.FCRMVP.USR_FCRMVP_ESTPK2, 'A') AS ESTPK2, 
dbo.getCodigosBarra(dbo.FCRMVI.FCRMVI_TIPPRO, dbo.FCRMVI.FCRMVI_ARTCOD) AS CODBAR,
ISNULL(dbo.FCRMVP.FCRMVP_NUBICA, '') AS NUBICA, 
ISNULL(dbo.FCRMVP.FCRMVP_NDESPA, '') AS NDESPA, 
ISNULL(dbo.FCRMVP.FCRMVP_NFECHA, '') AS NFECHA,  
dbo.FCRMVI.FCRMVI_MODAPL AS MODFOR, 
dbo.FCRMVI.FCRMVI_ITMAPL AS NROITM, 
dbo.FCRMVI.FCRMVI_EXPAPL AS NIVEXP, 
dbo.USR_SITIOS.USR_SITIOS_DESCRP AS SITDES, 
dbo.VTMCLH.VTMCLH_NOMBRE AS NOMBRE, 
dbo.GRTTRA.GRTTRA_TRACOD AS TRACOD, 
dbo.GRTTRA.GRTTRA_DESCRP AS TRADES, 
dbo.STMPDH.USR_STMPDH_NROPAR AS NROPAR, '--' AS CODPRO, 
dbo.STMPDH.STMPDH_UNIMED AS UNIMED, 
dbo.STMPDH.STMPDH_UNICON AS UNICON, 
dbo.STMPDH.STMPDH_FACCON AS FACCON, 
                      CONVERT(VARCHAR(255),
                          'http://sd-1330535-h00008.ferozo.net/imagenes/productos/' +
                          (SELECT     USR_STIMPR_IMGGRA
                            FROM          dbo.USR_STIMPR AS I
                            WHERE      (USR_STIMPR_ORDEN = 1) 
                            AND (USR_STIMPR_TIPPRO = dbo.FCRMVI.FCRMVI_TIPPRO) 
                            AND (USR_STIMPR_ARTCOD = dbo.FCRMVI.FCRMVI_ARTCOD)) + '.jpg') AS IMGPRD

FROM dbo.FCRMVH 
INNER JOIN dbo.FCRMVI ON 
		dbo.FCRMVH.FCRMVH_MODFOR = dbo.FCRMVI.FCRMVI_MODAPL 
	AND dbo.FCRMVH.FCRMVH_CODFOR = dbo.FCRMVI.FCRMVI_CODAPL 
	AND dbo.FCRMVH.FCRMVH_NROFOR = dbo.FCRMVI.FCRMVI_NROAPL 
LEFT OUTER JOIN dbo.FCRMVP ON dbo.FCRMVI.FCRMVI_MODFOR = dbo.FCRMVP.FCRMVP_MODFOR 
						AND dbo.FCRMVI.FCRMVI_CODFOR = dbo.FCRMVP.FCRMVP_CODFOR 
						AND dbo.FCRMVI.FCRMVI_NROFOR = dbo.FCRMVP.FCRMVP_NROFOR 
						AND dbo.FCRMVI.FCRMVI_NROITM = dbo.FCRMVP.FCRMVP_NROITM 
						AND dbo.FCRMVI.FCRMVI_NIVEXP = dbo.FCRMVP.FCRMVP_NIVEXP 
						AND dbo.FCRMVI.FCRMVI_TIPPRO = dbo.FCRMVP.FCRMVP_TIPPRO 
						AND dbo.FCRMVI.FCRMVI_ARTCOD = dbo.FCRMVP.FCRMVP_ARTCOD 
INNER JOIN dbo.STTTPH ON dbo.FCRMVI.FCRMVI_TIPPRO = dbo.STTTPH.STTTPH_TIPPRO 
INNER JOIN dbo.STMPDH ON dbo.FCRMVI.FCRMVI_TIPORI = dbo.STMPDH.STMPDH_TIPPRO 
					 AND dbo.FCRMVI.FCRMVI_ARTORI = dbo.STMPDH.STMPDH_ARTCOD 
INNER JOIN dbo.VTMCLH ON dbo.FCRMVH.FCRMVH_NROCTA = dbo.VTMCLH.VTMCLH_NROCTA 
INNER JOIN dbo.GRTTRA ON dbo.FCRMVH.FCRMVH_TRACOD = dbo.GRTTRA.GRTTRA_TRACOD 
INNER JOIN dbo.USR_SITIOS ON dbo.USR_SITIOS.USR_SITIOS_CODIGO = dbo.FCRMVH.USR_FCRMVH_SITIOS
WHERE (dbo.FCRMVI.FCRMVI_TIPORI BETWEEN '000' AND '999') 
AND (dbo.FCRMVH.FCRMVH_CIRCOM IN ('0250', '0260')) 
AND (dbo.FCRMVH.FCRMVH_DEBAJA = 'N') 
AND (dbo.FCRMVI.FCRMVI_DEBAJA = 'N') 
AND (dbo.STMPDH.STMPDH_DEBAJA = 'N') 
AND (dbo.FCRMVI.FCRMVI_TIPPRO <> '999') 
AND (ISNULL(dbo.FCRMVP.USR_FCRMVP_ESTPCK, 'A') = 'A' 
OR   ISNULL(dbo.FCRMVP.USR_FCRMVP_ESTPK2, 'A') = 'A') 
AND (dbo.FCRMVH.FCRMVH_FCHMOV > DATEADD(DAY, - 3, GETDATE()))
GROUP BY 
dbo.FCRMVI.FCRMVI_MODAPL,
dbo.FCRMVI.FCRMVI_CODAPL,
dbo.FCRMVI.FCRMVI_NROAPL,
dbo.FCRMVI.FCRMVI_ITMAPL,
dbo.FCRMVI.FCRMVI_EXPAPL,
dbo.FCRMVH.USR_FCRMVH_SITIOS,
dbo.USR_SITIOS.USR_SITIOS_DESCRP,
dbo.FCRMVH.FCRMVH_CIRCOM,
dbo.FCRMVP.FCRMVP_DEPOSI,
dbo.FCRMVH.FCRMVH_NROCTA,
dbo.VTMCLH.VTMCLH_NOMBRE,
dbo.GRTTRA.GRTTRA_TRACOD,
dbo.GRTTRA.GRTTRA_DESCRP,
dbo.FCRMVI.FCRMVI_TIPPRO,
dbo.FCRMVI.FCRMVI_ARTCOD,
dbo.STTTPH.STTTPH_DESCRP,
dbo.STMPDH.STMPDH_DESCRP,
dbo.STMPDH.USR_STMPDH_NROPAR,
ISNULL(dbo.FCRMVP.USR_FCRMVP_CNTPCK, 0), 
ISNULL(dbo.FCRMVP.USR_FCRMVP_CNTFST, 0), 
ISNULL(dbo.FCRMVP.USR_FCRMVP_ESTPCK, 'A'), 
ISNULL(dbo.FCRMVP.USR_FCRMVP_CNTPK2, 0), 
ISNULL(dbo.FCRMVP.USR_FCRMVP_ESTPK2, 'A'), 
ISNULL(dbo.FCRMVP.FCRMVP_NUBICA, ''), 
ISNULL(dbo.FCRMVP.FCRMVP_NDESPA, ''), 
ISNULL(dbo.FCRMVP.FCRMVP_NFECHA, ''), 
dbo.STMPDH.STMPDH_UNIMED, 
dbo.STMPDH.STMPDH_UNICON, 
dbo.STMPDH.STMPDH_FACCON,
dbo.FCRMVP.USR_FCRMVP_USRPCK, 
dbo.FCRMVP.USR_FCRMVP_USRPK2
HAVING (SUM(FCRMVP_CANTID)) > 0