
SELECT  dbo.CORMVI.CORMVI_MODAPL + dbo.CORMVI.CORMVI_CODAPL + CONVERT(VARCHAR, dbo.CORMVI.CORMVI_NROAPL) 
                      + dbo.CORMVI.CORMVI_TIPPRO + dbo.CORMVI.CORMVI_ARTCOD + ISNULL(dbo.CORMVI.USR_CORMVI_ESTPCK, 'A') + ISNULL(dbo.CORMVI.CORMVI_NUBICA, '') 
                      + ISNULL(dbo.CORMVI.CORMVI_NDESPA, '') AS ID, 
                      dbo.CORMVH.USR_CORMVH_SITIOS AS SITIOS, 
                      dbo.CORMVH.USR_CORMVH_SITDES AS SITDES,                       
                      dbo.CORMVH.CORMVH_CIRCOM AS CIRCOM, 
                      dbo.CORMVI.CORMVI_DEPOSI AS DEPOSI, 
                      SITDES.USR_SITIOS_DESCRP AS SITDES_DESCRP,
                      dbo.CORMVI.CORMVI_CODAPL AS CODFOR, 
                      dbo.CORMVI.CORMVI_NROAPL AS NROFOR, 
                      dbo.CORMVH.CORMVH_FCHMOV AS FCHMOV, 
                      dbo.CORMVH.CORMVH_NROCTA AS NROCTA, 
                      dbo.CORMVI.CORMVI_TIPPRO AS TIPPRO, 
                      dbo.CORMVI.CORMVI_ARTCOD AS ARTCOD, 
                      dbo.STTTPH.STTTPH_DESCRP AS TIPDES, 
                      dbo.STMPDH.STMPDH_DESCRP AS DESCRP, 
                      SUM(dbo.CORMVI.CORMVI_CANTID) AS CANTID, 
                      ISNULL(dbo.CORMVI.USR_CORMVI_CNTPCK, 0) AS CNTPCK, 
                      ISNULL(dbo.CORMVI.USR_CORMVI_CNTFST, 0) AS CNTFST, 
                      ISNULL(dbo.CORMVI.CORMVI_NUBICA, '') AS NUBICA, 
                      ISNULL(dbo.CORMVI.CORMVI_NDESPA, '') AS NDESPA, 
                      ISNULL(dbo.CORMVI.CORMVI_NFECHA, '') AS NFECHA, 
                      ISNULL(dbo.CORMVI.USR_CORMVI_USRPCK, '') AS USRPCK, 
                      ISNULL(dbo.CORMVI.USR_CORMVI_ESTPCK, 'A') AS ESTPCK,                       
                      dbo.getCodigosBarra(dbo.CORMVI.CORMVI_TIPPRO, dbo.CORMVI.CORMVI_ARTCOD) AS CODBAR, 
                      dbo.CORMVI.CORMVI_MODAPL AS MODFOR, dbo.CORMVI.CORMVI_ITMAPL AS NROITM, dbo.CORMVI.CORMVI_EXPAPL AS NIVEXP, dbo.USR_SITIOS.USR_SITIOS_DESCRP AS SITDES, 
                      dbo.PVMPRH.PVMPRH_NOMBRE AS NOMBRE, 
                      -- dbo.GRTTRA.GRTTRA_TRACOD AS TRACOD, 
                      -- dbo.GRTTRA.GRTTRA_DESCRP AS TRADES, 
                      dbo.STMPDH.USR_STMPDH_NROPAR AS NROPAR, 
                      '--' AS CODPRO, dbo.STMPDH.STMPDH_UNIMED AS UNIMED, dbo.STMPDH.STMPDH_UNICON AS UNICON, dbo.STMPDH.STMPDH_FACCON AS FACCON, CONVERT(VARCHAR(255), 
                      'http://sd-1330535-h00008.ferozo.net/imagenes/productos/' +
                          (SELECT     USR_STIMPR_IMGGRA
                            FROM          dbo.USR_STIMPR AS I
                            WHERE      (USR_STIMPR_ORDEN = 1) AND (USR_STIMPR_TIPPRO = dbo.CORMVI.CORMVI_TIPPRO) AND (USR_STIMPR_ARTCOD = dbo.CORMVI.CORMVI_ARTCOD)) + '.jpg') AS IMGPRD
FROM         dbo.CORMVH INNER JOIN
                      dbo.CORMVI ON dbo.CORMVI.CORMVI_MODAPL = dbo.CORMVH.CORMVH_MODFOR AND dbo.CORMVI.CORMVI_CODAPL = dbo.CORMVH.CORMVH_CODFOR AND 
                      dbo.CORMVI.CORMVI_NROAPL = dbo.CORMVH.CORMVH_NROFOR INNER JOIN
                      dbo.STTTPH ON dbo.CORMVI.CORMVI_TIPPRO = dbo.STTTPH.STTTPH_TIPPRO INNER JOIN
                      dbo.STMPDH ON dbo.CORMVI.CORMVI_TIPORI = dbo.STMPDH.STMPDH_TIPPRO AND dbo.CORMVI.CORMVI_ARTORI = dbo.STMPDH.STMPDH_ARTCOD INNER JOIN
                      dbo.PVMPRH ON dbo.CORMVH.CORMVH_NROCTA = dbo.PVMPRH.PVMPRH_NROCTA 
INNER JOIN dbo.USR_SITIOS ON dbo.USR_SITIOS.USR_SITIOS_CODIGO = dbo.CORMVH.USR_CORMVH_SITIOS
INNER JOIN dbo.USR_SITIOS AS SITDES ON SITDES.USR_SITIOS_CODIGO = dbo.CORMVH.USR_CORMVH_SITDES
WHERE (dbo.CORMVH.CORMVH_CIRCOM IN ('3050')) 
AND (dbo.CORMVH.CORMVH_DEBAJA = 'N') 
AND (dbo.STMPDH.STMPDH_DEBAJA = 'N') 
AND (dbo.CORMVH.CORMVH_FCHMOV > DATEADD(DAY, - 365, GETDATE())) 
AND (ISNULL(dbo.CORMVI.USR_CORMVI_ESTPCK, 'A') = 'A') 
AND (dbo.CORMVI.CORMVI_TIPPRO BETWEEN '000' AND '999') 
AND (dbo.CORMVI.CORMVI_DEBAJA = 'N') 
AND (dbo.CORMVI.CORMVI_TIPPRO <> '999')
GROUP BY dbo.CORMVI.CORMVI_MODAPL, 
dbo.CORMVI.CORMVI_CODAPL, 
dbo.CORMVI.CORMVI_NROAPL, 
dbo.CORMVI.CORMVI_ITMAPL, 
dbo.CORMVI.CORMVI_EXPAPL, 
dbo.CORMVH.USR_CORMVH_SITIOS, 
dbo.CORMVH.USR_CORMVH_SITDES,
dbo.CORMVH.CORMVH_FCHMOV,
SITDES.USR_SITIOS_DESCRP,
dbo.USR_SITIOS.USR_SITIOS_DESCRP, 
dbo.CORMVH.CORMVH_CIRCOM, 
dbo.CORMVI.CORMVI_DEPOSI, 
dbo.CORMVI.CORMVI_DEPTRA,
dbo.CORMVH.CORMVH_NROCTA, 
dbo.PVMPRH.PVMPRH_NOMBRE,                       
dbo.CORMVI.CORMVI_TIPPRO, dbo.CORMVI.CORMVI_ARTCOD, dbo.STTTPH.STTTPH_DESCRP, 
                      dbo.STMPDH.STMPDH_DESCRP, dbo.STMPDH.USR_STMPDH_NROPAR, ISNULL(dbo.CORMVI.USR_CORMVI_CNTPCK, 0), ISNULL(dbo.CORMVI.USR_CORMVI_CNTFST, 0), 
                      ISNULL(dbo.CORMVI.USR_CORMVI_ESTPCK, 'A'), 

ISNULL(dbo.CORMVI.CORMVI_NUBICA, ''), 
ISNULL(dbo.CORMVI.CORMVI_NDESPA, ''), 
ISNULL(dbo.CORMVI.CORMVI_NFECHA, ''), 
dbo.STMPDH.STMPDH_UNIMED, 
dbo.STMPDH.STMPDH_UNICON, 
dbo.STMPDH.STMPDH_FACCON, 
dbo.CORMVI.USR_CORMVI_USRPCK
HAVING (SUM(dbo.CORMVI.CORMVI_CANTID) > 0)